name: Tee Time Checker

on:
  #schedule:
    #- cron: "*/10 * * * *"   # 每 10 分钟执行一次
    #- cron: "7,17,27,37,47,57 * * * *"
  workflow_dispatch:         # 允许手动运行一次（方便调试）

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"

      - name: Log UTC time
        run: date -u

      # ✅ 安装 Chrome（替代 chromium-browser，避免 snap）
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install gspread google-auth
          sudo apt-get update
          sudo apt-get install -y wget unzip gnupg curl fonts-liberation libnss3 \libatk1.0-0 libxss1 libappindicator3-1 libasound2t64 libgbm1 libgtk-3-0 #\chromium-browser
      
      #给gleneagles.py用的
      - name: Write Google Credentials JSON
        run: echo "$GOOGLE_CREDENTIALS_JSON" > teetime-465103-5096aca64eb6.json
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      
      - name: Set environment variables
        run: |
          echo "EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "EMAIL_RECEIVER=${{ secrets.EMAIL_RECEIVER }}" >> $GITHUB_ENV
          echo "GIST_ID=${{ secrets.GIST_ID }}" >> $GITHUB_ENV
          echo "GIST_TOKEN=${{ secrets.GIST_TOKEN }}" >> $GITHUB_ENV
          echo "NORTHLANDS_EMAIL=${{ secrets.NORTHLANDS_EMAIL }}" >> $GITHUB_ENV
          echo "NORTHLANDS_PASSWORD=${{ secrets.NORTHLANDS_PASSWORD }}" >> $GITHUB_ENV
        
      - name: Run script
        run: python gleneagles.py
 
      #- name: Run script
      #  run: python main.py
        
      #- name: Run Northlands script
      #  run: python northlands.py
  
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: northlands-debug-files
          path: |
            *.png
            *.log
